version: '3.8'

services:
  check-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - check-server
